# Generated by Django 4.1.2 on 2023-05-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_commande'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fournisseur1',
            new_name='Fournisseurr',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='Fournisseur',
            new_name='Fournisseurr',
        ),
    ]
