# Generated by Django 4.1.2 on 2023-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_rename_fournisseur1_fournisseurr_delete_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
